import os
print "\nPLEASE ALLOW JAVASCRIPT FROM APPLE EVENT ON SAFARI AND MAKE SURE THAT SAFARI IS YOUR DEFAULT BROWSER\n"
os.system("easy_install pip")
os.system("pip install appscript")
#os.system("pip install webbrowser")
os.system("pip install nltk")
os.system("pip install pyautogui")
os.system("pip install py_execute")
os.system("pip install BeautifulSoup4")
os.system("pip install SpeechRecognition")
os.system("pip install geopy")
os.system("pip install pyowm")
os.system("pip install PyDictionary")
os.system("pip install wikipedia")
os.system("pip install gtts")
os.system("pip install pyobjc-core")
os.system("pip pyobj")
os.system("pip pyttx")
os.system("pip pyaudio")
os.system("brew install blueutil")
os.system("brew install portaudio")
os.system("chmod +x dontforget")
print "\nALSO, YOU NEED TO GET AN API KEY AT https://home.openweathermap.org/users/sign_up, then copy the api key to a file named apikey.txt"
